### ISSUE TITLE
.then() not waiting for Promise function to resolve

### ISSUE THREAD

**Issue by joey2031** [joey2031/OSD600-Release0.1#11]
On the issue-9 branch in <a href="https://github.com/joey2031/OSD600-Release0.1/blob/issue-9/BrokenLinkChecker-%20Release%200.1/index.js"> index.js</a> the function call to makeCalls is not waiting for it to resolve. MakCalls sets the value of allGood but for some reason, it's executing any code I put in the then() first.
```javascript
        makeCalls().then(() => {
            console.log(allGood)
            console.log("Done");
        }).catch((err) => {
            console.log(err)
        });
```
Output:
![image](https://user-images.githubusercontent.com/36198917/95219476-68035c80-07c3-11eb-9d55-c8255290aac5.png)

**Comment by humphd** [comment]
Move the `resolve()` at https://github.com/joey2031/OSD600-Release0.1/blob/issue-9/BrokenLinkChecker-%20Release%200.1/index.js#L90 inside the `then().catch()` after the request has completed.

What's happening is that you're immediately resolving the promise before the network request completes.

**Comment by joey2031** [comment]
@humphd 
```javascript
function makeCalls() {
    return new Promise(function (resolve, reject) {
        for (let i = 0; i < linkArr.length; i++) {
            //console.log(allGood);
            fetch(linkArr[i], { method: "HEAD" }).then(response => {
                if (response.status == 200) { // good
                    console.log(`${linkArr[i]} was good! status: ${response.status}`.green);
                } else if (response.status == 404 || response.status == 401) { // bad
                    console.log(`${linkArr[i]} was bad! status: ${response.status}`.red);
                    allGood = false; 
                   // console.log(allGood);
                } else { // unknown
                    console.log(`${linkArr[i]} was unknown! status: ${response.status}`.gray);
                }

            }).then(() => { 
                //DNS resolver 
                var linkN = linkArr[i].toString().replace(/(^\w+:|^)\/\//, '');
                dns.resolve(linkN, rrtype, (err, records) => console.log('records: %j', records))
                resolve(); // Moved resolve() here
            }).catch((err) => {
                    console.log(err)
                });
        } 
    })
}
```
This is what you meant right? It works when I use text.txt but not test.html also "Done" is still being printed before the function executes. Also, I just noticed this is all in the for loop, could that be causing problems? Thanks

**Comment by humphd** [comment]
You are running a loop inside your Promise, so you actually have a lot of them.  Use an Array of Promises with Promise.all, something like this:

```js
function makeCalls() {
  return Promise.all(linkArr.map(link => fetch(link, {...}).then(response => {...}).catch(err => {...})));
}
```

**Comment by joey2031** [comment]
@humphd Just realized and was working on that could I also just move the promise inside the for loop?  
```javascript
 for (let i = 0; i < linkArr.length; i++) {
        return new Promise(function (resolve, reject) {
```
ill also research an Array of Promises, I was wondering about the promise inside the for loop for learning purposes.

**Comment by humphd** [comment]
If you return in your loop, you won't have a loop anymore (i.e., single iteration and it's done).

Loops and async calls are tricky.  A loop goes over things that exist now: a collection of Objects.  But, you don't have the Objects that you need for the future async call.  So a Promise a way to get an Object now that you can work with, even though it doesn't have a value yet.

So you need to convert a list of things you have now (i.e., `links`) to list of Promises:

```
links.map(link => createPromiseForThisLink(link))
```

Now you can use Promise.all to wait on all those separate link Promises as if they were a single Promise.
