### ISSUE TITLE
more unit test for `makeCalls`

### ISSUE THREAD

**Issue by klee214** [joey2031/OSD600-Release0.1#23]
### Problem
So far, `makeCalls` is only tested if there is actual link whether it is valid or not. However, for some reasons (Connection fail, router problem...) undefined or null value can be passed instead of link.

We should hand this error either!

### Suggestion
Create a one more unit test for this. Like 
`test("Pass array with undefined, empty array and null to makeCalls should return empty array", ...)`

**Comment by joey2031** [comment]
Hmm, I never thought of that, good idea! Thanks, I see u already made a PR, looks good, gonna merge!
