### ISSUE TITLE
node_modules doesn't need to exist 

### ISSUE THREAD

**Issue by fluentinstroll** [joey2031/OSD600-Release0.1#4]
The node_modules folder provides unnecessary bloat to the repo and can simply be removed.

I suggest removing the node_modules folder and pushing again then adding a .gitignore (https://docs.github.com/en/github/using-git/ignoring-files) to your git in order to avoid pushing your node_modules folder.

**Comment by joey2031** [comment]
Talked to my professor, turns out it's going to be very hard to get rid of them, I will keep this at the back of my mind in the future and just add them to .gitignore
